apiVersion: v1
kind: Service
metadata:
  name: postgres_service
  labels:
    app: postgres_service
spec:
  selector:
    app: postgres_service
    tier: postgres
  ports:
  - name: db
    port: 5432
    targetPort: 5432
