apiVersion: v1
kind: Service
metadata:
  namespace: book-store
  name: postgres-database-live
  labels:
    app: postgres-database-live
spec:
  selector:
    app: postgres-database-live
    tier: postgres
  ports:
  - name: db
    port: 5432
    targetPort: 5432
